### ISSUE TITLE
[MessageAttributes] must be an associative array.

### ISSUE THREAD

**Issue by Harveyhase68** [tedicela/sqs-simple#3]
Fatal error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the SendMessage operation: [MessageAttributes] must be an associative array. Found <pre class='xdebug-var-dump' dir='ltr'> <small>C:\wamp3\www\amazon\vendor\aws\aws-sdk-php\src\functions.php:263:</small><small>int</small> <font color='#4e9a06'>10</font> </pre> in C:\wamp3\www\amazon\vendor\aws\aws-sdk-php\src\Api\Validator.php on line 65

InvalidArgumentException: Found 1 error while validating the input provided for the SendMessage operation: [MessageAttributes] must be an associative array. Found <pre class='xdebug-var-dump' dir='ltr'> <small>C:\wamp3\www\amazon\vendor\aws\aws-sdk-php\src\functions.php:263:</small><small>int</small> <font color='#4e9a06'>10</font> </pre> in C:\wamp3\www\amazon\vendor\aws\aws-sdk-php\src\Api\Validator.php on line 65

Call Stack
#	Time	Memory	Function	Location
1	0.0001	358816	{main}( )	...\index.php:0
2	0.0080	527624	SqsSimple\SqsMessenger->publish( )	...\index.php:31
3	0.0080	527928	Aws\Sqs\SqsClient->sendMessage( )	...\SqsMessenger.php:95
4	0.0080	528200	Aws\Sqs\SqsClient->__call( )	...\SqsMessenger.php:95
5	0.0082	530168	Aws\Sqs\SqsClient->execute( )	...\AwsClientTrait.php:86
6	0.0082	530168	Aws\Sqs\SqsClient->executeAsync( )	...\AwsClientTrait.php:58
7	0.0082	535248	Aws\IdempotencyTokenMiddleware->__invoke( )	...\AwsClientTrait.php:64
8	0.0086	542816	Aws\Middleware::Aws\{closure:C:\wamp3\www\amazon\vendor\aws\aws-sdk-php\src\Middleware.php:70-81}( )	...\IdempotencyTokenMiddleware.php:77
9	0.0086	542816	Aws\Api\Validator->validate( )	...\Middleware.php:78

PHP 7.2 on WampServer in Windows... what did I wrong??

I installed all required with composer, then I added a index.php like your "How to publish messages into an SQS queue" example, without changes (except Keys and URL)

I think this is a AWS problem, which AWS SDK version should I use??

**Comment by tedicela** [comment]
Hi @Harveyhase68 ,

First of all sorry for the late reply.

There is no problem with AWS. But I found out that the README wasn't updated correctly. Now is updated. 

The problem was: the 3rd argument in `publish` is `$messageAttributes` which should be an array. 

```
$messenger->publish( $queue, $message, $messageAttributes, $delaySeconds, $messageGroupId, $messageDeduplicationId);
```

**Comment by Harveyhase68** [comment]
Thx for the reply, atm it worked with the SQS AWS example from Amazon directly.

This weekend I'll try again, empty project, add composer and launch, because your project is far easier to maintain.

Yours Alex
